# .github/workflows/deploy.yaml
name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    # Step 3: Build Docker image
    - name: Build Docker image
      run: |
        docker build -t python-app:latest .

    # Step 4: Log in to your HPC via SSH and push Docker image to HPC Docker registry
    - name: Push Docker image to HPC
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HPC_HOST }}
        username: ${{ secrets.HPC_USER }}
        key: ${{ secrets.HPC_SSH_KEY }}
        port: ${{ secrets.HPC_PORT }}
        script: |
          docker login -u your-username -p your-password your-hpc-ip:5000
          docker build -t your-hpc-ip:5000/python-app:latest .
          docker push your-hpc-ip:5000/python-app:latest

    # Step 5: Deploy Docker image to Kubernetes on your HPC
    - name: Deploy to Kubernetes
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HPC_HOST }}
        username: ${{ secrets.HPC_USER }}
        key: ${{ secrets.HPC_SSH_KEY }}
        port: ${{ secrets.HPC_PORT }}
        script: |
          kubectl apply -f k8s-deployment.yaml
