name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Change this to your default branch if needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false  # Set to true if you want to push the image to a registry
        tags: myapp:latest  # Change this to your preferred image name

    - name: Deploy to Kubernetes
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'
      
    - name: Set Kubernetes context
      run: |
        kubectl config set-context my-cluster --namespace=default

    - name: Apply Kubernetes deployment
      run: |
        kubectl apply -f k8s/deployment.yaml  # Adjust the path to your Kubernetes config
